### PR TITLE
[ISSUE 315] Move apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by hantmac**
Signed-off-by: hantmac <hantmac@outlook.com>

- Move apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1
- fix [Issue 315](https://github.com/streamnative/function-mesh/issues/315)

### CODE REVIEW

**Review by fantapsody — APPROVED** [review]

**Comment by hantmac** [comment]
We need to use `kubectl conver` to convert the `apiextensions.k8s.io/v1` to `apiextensions.k8s.io/v1beta1` in `function-mesh/config/crd/patches`, but the kube version in my machine can't do this beacause I don't have the lower version.

image

So can you do the `kubectl convert` ?

**Comment by freeznet** [comment]
@hantmac I have tried with the convert plugin, seems we need to use a lower version's `kubectl` and related client release to do this. lets try use the kubectl image like https://hub.docker.com/r/bitnami/kubectl

**Comment by hantmac** [comment]
> @hantmac I have tried with the convert plugin, seems we need to use a lower version's `kubectl` and related client release to do this. lets try use the kubectl image like https://hub.docker.com/r/bitnami/kubectl

Yes, I have done this convert. But we need to modify the k8s version in github ci, wait for me.

**Comment by hantmac** [comment]
@freeznet I guess the helm chart of `local-storage-provisioner` is not newest, the version of DaemonSet in it is `extensions/v1beta1`, I have made [this issue](https://github.com/streamnative/charts/issues/502)

**Comment by freeznet** [comment]
thanks @hantmac, from my experience, the `local-storage-provisioner` might not a MUST have service in the test environment, so maybe we can simplifier the Github Action script to make the Pulsar install minimal (see https://github.com/streamnative/function-mesh/pull/331)

**Comment by hantmac** [comment]
@freeznet  Copy that.

**Review by freeznet — APPROVED** [review]

**Pull request merged**
