### PR TITLE
Sync function/source/sink configdata to pod when updated.

### PR DESCRIPTION
**Pull request by MarvinCai**
resolve: https://github.com/streamnative/function-mesh/issues/216
Add a annotation for hash of applied configdata to compare diff of applied config and current config, update pod if hash doesn't match.

### CODE REVIEW

**Comment by nlu90** [comment]
@MarvinCai  could you please rebase your branch with the current master branch?

**Review by freeznet — COMMENTED** [review]
@MarvinCai thanks, and this PR LGTM, but I do have one question here. 

For function-mesh, the annotation of `Function`, `Sink` or `Source` will not be transferred to statefulset's pod template, will the `configHash` still be able to trigger the pod recreation process? I do noticed that the tests added in this PR is trying to verify the new config been synced to the pod's command, but will this command changes trigger the recreation of pods? If not, then the pods will still running with the old config data.

We have to make sure the changes will be updated to the pod.

ref: https://github.com/streamnative/function-mesh/blob/v0.1.7/controllers/spec/common.go#L584

**Comment by nlu90** [comment]
@MarvinCai and @freeznet , can we prioritize this issue to unblock cloud team?

**Comment by MarvinCai** [comment]
To your original comment, we're not trying to sync annotation to statefulset, just need to use that as a flag to indicate if statefulset need to be updated.
But after discussion with Yangyang offline, there's no need to do that as for function configs directly applied to statefulset command, so we can simply compare desired statefulset spec with current statefulset spec to determine if statefulset need to be update.

**Review by freeznet — APPROVED** [review]
Thanks @MarvinCai, lgtm.

**Pull request merged**
