### PR TITLE
upgrade to `k8s.io/api/autoscaling/v2beta2`

### PR DESCRIPTION
**Pull request by freeznet**
- upgrade `autoscaling/v1` to `autoscaling/v2beta2`
- add default HPA to make `maxReplicas` backward compatibility 
- add `autoScalingMetrics` and `autoScalingBehavior` to `PodPolicy` to allow user customize `HorizontalPodAutoscalerSpec`
- add `builtinAutoscaler` to support builtin HPA rules
- add builtin HPA rules
- add integration test of HPA and Builtin HPA
- add metrics-server to integration test kind cluster

### CODE REVIEW

**Comment by freeznet** [comment]
@nlu90 @fantapsody @tuteng Please help to review this PR when you have time, thanks.

**Comment by fantapsody** [comment]
It seems we'll need user inputs to customize the autocaling metrics and behavior but I think might not be easy for users to determine a proper policy. Is it possible for us to put more best practices into the controller like what metrics and behavior should be used in general or for certain kinds of workloads (CPU/IO/Network/... intense) to make the operator easy to use?

**Comment by freeznet** [comment]
@fantapsody thanks for the comment. We can provide some general kinds of workloads to make function-mesh more user friendly. But if we want to support the custom metrics provided by the specified Pulsar IO Connector, the harder way is still needed as well. So what do you think if we keep the current design, but provide an extra config like `builtinAutoscaler` and provide a bunch of pre-defined metrics and behaviours pair to let the user use?

**Comment by fantapsody** [comment]
Sounds good.

**Comment by freeznet** [comment]
@fantapsody just added builtin rules and tests, PTAL when you have time, thanks.

**Review by tuteng — APPROVED** [review]

**Review by nlu90 — APPROVED** [review]

**Review by fantapsody — APPROVED** [review]

**Pull request merged**
