### PR TITLE
Update release v0.5.0 version

### PR DESCRIPTION
**Pull request by danpi**
### Motivation

Bump version to 0.5.0 for master branch

### Modifications

Bump version to 0.5.0 for master branch

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

Check the box below.

Need to update docs? 

  
- [x] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by tpiperatgod — APPROVED** [review]
lgtm

**Comment by tpiperatgod** [comment]
the [compatibility matrix](https://github.com/streamnative/function-mesh#kubernetes-compatibility-matrix) also needs to be updated

**Review by freeznet — APPROVED** [review]
lgtm, please refer to @tpiperatgod 's comment, to add the matrix as well.

**Comment by nlu90** [comment]
👍🏼

**Pull request merged**
